### ISSUE TITLE
account

### ISSUE THREAD

**Issue by Maradan974** [OwOHamper/Valorant-item-shop-discord-bot#1]
hey, is there a way to get the store for everyone not just the account i put in?

**Comment by teoobarca** [comment]
No, unfortunately store uses in-game api which can only be accesed by JWT entitlement token, and Bearer token, and those you can get onyl by riot account username and password.

**Comment by Maradan974** [comment]
I know I meant like they put their accounts too by logging in with the bot or something like that

**Comment by teoobarca** [comment]
Sorry for late reply, but ye you could store everyone username passwords, however it's way to dangerous you can instead store the entitlements using cookies https://github.com/techchrism/riot-auth-test. If you want to make large-scale bot I wouldn't recommend mine but rewriting it.
