### ISSUE TITLE
Images not loading once i ay !shop

### ISSUE THREAD

**Issue by Swft10** [OwOHamper/Valorant-item-shop-discord-bot#7]
its says this when i type !shop
![image](https://user-images.githubusercontent.com/93814702/140600509-0eef9632-edf7-4e71-843c-a9d35d1f1f61.png)
PLEASE HELP!!!!

**Comment by teoobarca** [comment]
did you tried restarting?

**Comment by Swft10** [comment]
yes i have

**Comment by teoobarca** [comment]
The region is not correct
